---
title: "SRT411assignment0"
author: "juan zhao"
date: "February 2, 2017"
output:
  html_document: default
  pdf_document: default
---


#3.1 ToDo
```{r}
(2017-2014)/(2014-1985)*100
```
#3.2 TODO
```{r}
Cur_Year = 2017
My_Birth = 1985
(Cur_Year - 2014)/(2014 - My_Birth)*100
```
#3.4 TODO
```{r}
a=c(4,5,8,11)
sum(x=a)
```
#3.5 TODO
```{r}
x = rnorm(100)
plot(x)
```
#4.0 TODO
```{r}
help(sqrt)
```
#6.0 TODO
```{r}
P = seq(31,60)
Q = matrix(data=P, ncol=5,nrow=6)
P
Q
```
#5.0 TODO
```{r}
earrings = 1
while (earrings < 6) {
  plot(rnorm(100))
  earrings = earrings+1
}

```

#6.3 TODO
```{r}
x1 =c(rnorm(100))
x2 = c(rnorm(100))
x3 = c(rnorm(100))
t = data.frame(a=x1,b=x1+x2,c=x1+x2+x3 )
plot(t)

```
#7.0 TODO
```{r}
plot(t$a, type="l", ylim=range(t),lwd=3, col=rgb(1,0,0,0.3))
lines(t$b, type="s", lwd=2,col=rgb(0.3,0.4,0.3,0.9))
points(t$c, pch=20, cex=4,col=rgb(0,0,1,0.3))
```


#8.0 TODO
```{r}
D8= read.table(file = "/home/juan/SRT411/SRT411-Assignment-0/tst1.txt", header =TRUE)
write.table(D8$g*5, file=  "/home/juan/SRT411/SRT411-Assignment-0/tst1.txt",row.names=FALSE)
D8

```
#9.0 TODO
```{r}
##V9=c(rnorm(100), na.rm=TRUE)
V9=c(runif(n=100, min=0, max=100))
V9
j=c(1,2,NA)
max(j)
max(j,na.rm = TRUE)
max(V9, na.rm=TRUE)
mean(sqrt(V9), na.rm = TRUE)

```
#10.2 Dates 
```{r}
date1=strptime(c("20170201","20171225","20170216"),format = "%Y%m%d")

d<- data.frame(date1=c("20170201","20171225","20170216"),presents=c("2","3","4"))
##d<- data.frame(date1,presents=c("2","3","4"))
x<-d$date1
y<-d$prensents

plot(x,y,xlab="date1",ylab="presents")
```
#11.2 TODO
```{r}
s=c()
for(i in 1:100)
 {if (i<5 | i >90)
   {s[i]=i * 10
   }else{
   s[i]=i*0.1
   }
}
s
```
#11.3 TODO
```{r}
fun1=function(arg1,arg2)
{
s=c()
for(i in arg1:arg2)
 {if (i<5 | i >90)
   {s[i]=i * 10
   }else{
   s[i]=i*0.1
   }
}
s
}
fun1(arg1=3,arg2=50)
```

